CREATE TABLE EQUIPO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO_EQUIPO CHAR(2),
    NOMBRE VARCHAR(20) NOT NULL,
    CONSTRAINT ID_EQUIPO_PK PRIMARY KEY (ID)
);

CREATE TABLE PILOTO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(30),
    EQUIPO INTEGER,
    FECHA_NACIMIENTO DATE,
    NUM_TITULOS SMALLINT,
    SALARIO DECIMAL(7,2),
    CAMPEON BOOLEAN,
    ESTILO_PILOTAJE CHAR(1),
    FOTO VARCHAR(30),
    CONSTRAINT ID_PILOTO_PK PRIMARY KEY (ID),
    CONSTRAINT EQUIP_PILOTO_FK FOREIGN KEY (EQUIPO) REFERENCES EQUIPO (ID)
);